#!/bin/bash
# generate-crontab.sh — Read bot.yaml and output a complete crontab to stdout.
#
# Can be run locally (for deploy.sh) or on the instance (for git-pull auto-sync).
#
# Usage:
#   ./generate-crontab.sh [path/to/bot.yaml]
#
# If no path is given, falls back to $BOT_HOME/bot.yaml (default: /opt/claude-bot/bot.yaml).
# Requires: yq

set -euo pipefail

# ── Resolve bot.yaml path ─────────────────────────────────────────────────────
BOT_YAML="${1:-}"
if [ -z "$BOT_YAML" ]; then
  BOT_HOME="${CLAUDE_BOT_HOME:-/opt/claude-bot}"
  BOT_YAML="$BOT_HOME/bot.yaml"
fi

if [ ! -f "$BOT_YAML" ]; then
  echo "Error: bot.yaml not found at $BOT_YAML" >&2
  exit 1
fi

if ! command -v yq &>/dev/null; then
  echo "Error: yq is not installed. Install with: brew install yq (macOS) or see https://github.com/mikefarah/yq" >&2
  exit 1
fi

# ── Helper: read a value from bot.yaml with a default ─────────────────────────
_yaml() {
  yq -r "$1" "$BOT_YAML" 2>/dev/null || echo "$2"
}

# ── Read config values ────────────────────────────────────────────────────────
BOT_NAME=$(_yaml '.name // "claude-bot"' "claude-bot")
SCRIPTS_DIR="/opt/claude-bot/scripts"
LOG_DIR="/var/log/$BOT_NAME"

# Infrastructure cron intervals
GIT_PULL_INTERVAL=$(_yaml '.infrastructure.git_pull_interval // "* * * * *"' "* * * * *")
SOCKET_WATCHDOG_INTERVAL=$(_yaml '.infrastructure.socket_watchdog_interval // "*/5 * * * *"' "*/5 * * * *")
STALE_LOCK_INTERVAL=$(_yaml '.infrastructure.stale_lock_interval // "*/5 * * * *"' "*/5 * * * *")
QUEUE_DRAIN_INTERVAL=$(_yaml '.infrastructure.queue_drain_interval // "* * * * *"' "* * * * *")
HEALTH_CHECK_TIME=$(_yaml '.infrastructure.health_check_time // "0 6 * * *"' "0 6 * * *")
LABEL_DISPATCHER_INTERVAL=$(_yaml '.infrastructure.label_dispatcher_interval // "* * * * *"' "* * * * *")

# GitHub settings
GITHUB_ENABLED=$(_yaml '.github.enabled // false' "false")
GITHUB_NOTIFICATIONS=$(_yaml '.github.notifications // false' "false")
GITHUB_NOTIFICATION_INTERVAL=$(_yaml '.github.notification_interval // "* * * * *"' "* * * * *")

# Slack settings
SLACK_SOCKET_MODE=$(_yaml '.slack.socket_mode // false' "false")

# ── Output crontab ────────────────────────────────────────────────────────────

cat <<EOF
# ═══════════════════════════════════════════════════════════════════════════════
# ${BOT_NAME} Crontab (auto-generated by generate-crontab.sh)
# ═══════════════════════════════════════════════════════════════════════════════

# ── Infrastructure (always running) ──────────────────────────────────────────
${GIT_PULL_INTERVAL} ${SCRIPTS_DIR}/git-pull.sh >> ${LOG_DIR}/cron.log 2>&1
${STALE_LOCK_INTERVAL} ${SCRIPTS_DIR}/clear-stale-locks.sh
${QUEUE_DRAIN_INTERVAL} ${SCRIPTS_DIR}/process-queue.sh >> ${LOG_DIR}/cron.log 2>&1
${HEALTH_CHECK_TIME} ${SCRIPTS_DIR}/bot-health-check.sh >> ${LOG_DIR}/cron.log 2>&1
EOF

# Socket watchdog (only if Slack socket mode is enabled)
if [ "$SLACK_SOCKET_MODE" = "true" ]; then
  echo "${SOCKET_WATCHDOG_INTERVAL} ${SCRIPTS_DIR}/check-socket-mode.sh >> ${LOG_DIR}/cron.log 2>&1"
fi

echo ""

# ── Label-driven dispatcher ──────────────────────────────────────────────────
cat <<EOF
# ── Label-driven dispatcher (scans for bot:* labels) ────────────────────────
${LABEL_DISPATCHER_INTERVAL} ${SCRIPTS_DIR}/workspace-dispatcher.sh >> ${LOG_DIR}/workspace-dispatcher.log 2>&1
EOF

# ── GitHub notifications ──────────────────────────────────────────────────────
if [ "$GITHUB_ENABLED" = "true" ] && [ "$GITHUB_NOTIFICATIONS" = "true" ]; then
  cat <<EOF

# ── GitHub notifications ─────────────────────────────────────────────────────
${GITHUB_NOTIFICATION_INTERVAL} ${SCRIPTS_DIR}/check-github.sh >> ${LOG_DIR}/cron.log 2>&1
EOF
fi

# ── Scheduled workspace jobs ─────────────────────────────────────────────────
# Read schedule names from bot.yaml and emit a cron line for each enabled one.
SCHEDULE_KEYS=$(_yaml '.schedules | keys | .[]' "")

if [ -n "$SCHEDULE_KEYS" ]; then
  cat <<EOF

# ── Scheduled workspace jobs ─────────────────────────────────────────────────
# Note: scheduled jobs use a reduced concurrency limit (MAX_CONCURRENT - RESERVED_INTERACTIVE),
# reserving slots for interactive work (GitHub mentions, Slack messages).
EOF

  while IFS= read -r schedule_name; do
    [ -z "$schedule_name" ] && continue

    enabled=$(_yaml ".schedules.\"${schedule_name}\".enabled // false" "false")
    if [ "$enabled" != "true" ]; then
      continue
    fi

    cron=$(_yaml ".schedules.\"${schedule_name}\".cron // \"\"" "")
    prompt=$(_yaml ".schedules.\"${schedule_name}\".prompt // \"\"" "")

    if [ -z "$cron" ] || [ -z "$prompt" ]; then
      echo "# WARNING: schedule '$schedule_name' missing cron or prompt — skipped" >&2
      continue
    fi

    echo "${cron} ${SCRIPTS_DIR}/workspace-dispatcher.sh --scheduled ${schedule_name} \"${prompt}\" >> ${LOG_DIR}/workspace-dispatcher.log 2>&1"
  done <<< "$SCHEDULE_KEYS"
fi
