#!/bin/bash
# cleanup-agent.sh — Cleanup function for EXIT trap.
# Sourced by run-claude.sh. Expects: LOCKFILE, AGENT_HOME, ACTIVE_DIR,
# HEARTBEAT_DIR, PROJECT_CHECKOUT, PROMPT_FILE, WORKTREE_DIR, LOGFILE,
# BOT_NAME, WORKSPACES_DIR, BASE_WORKSPACES_DIR

cleanup() {
  rm -f "$LOCKFILE"
  rm -f "$HEARTBEAT_DIR/heartbeat-$$.txt" 2>/dev/null || true
  # Stop the background heartbeat updater
  kill "$HEARTBEAT_UPDATER_PID" 2>/dev/null || true

  if [ -d "$AGENT_HOME" ]; then
    # Log unread messages so they are not silently lost
    UNREAD_DIR="$AGENT_HOME/inbox/unread"
    UNREAD_COUNT=0
    if [ -d "$UNREAD_DIR" ]; then
      UNREAD_COUNT=$(find "$UNREAD_DIR" -name "*.md" 2>/dev/null | wc -l)
    fi
    if [ "$UNREAD_COUNT" -gt 0 ]; then
      echo "[$(date)] WARNING: $UNREAD_COUNT unread message(s) in agent-$$ inbox at exit" >> "$LOGFILE"
      for UNREAD_FILE in "$UNREAD_DIR"/*.md; do
        [ -f "$UNREAD_FILE" ] || continue
        echo "[$(date)] Unread message ($(basename "$UNREAD_FILE")):" >> "$LOGFILE"
        cat "$UNREAD_FILE" >> "$LOGFILE" 2>/dev/null || true
      done
    fi

    # Remove symlinks from workspace stage output/ directories
    if [ -f "$AGENT_HOME/route.json" ]; then
      ROUTE_WS=$(jq -r '.workspace // empty' "$AGENT_HOME/route.json" 2>/dev/null)
      ROUTE_STAGE=$(jq -r '.stage // empty' "$AGENT_HOME/route.json" 2>/dev/null)
      if [ -n "$ROUTE_WS" ] && [ -n "$ROUTE_STAGE" ]; then
        # Try project workspaces first, then base workspaces
        RESOLVED_WS_PATH=$(resolve_workspace "$ROUTE_WS" 2>/dev/null || echo "")
        if [ -n "$RESOLVED_WS_PATH" ]; then
          SYMLINK_PATH="${RESOLVED_WS_PATH}/stages/${ROUTE_STAGE}/output/agent-$$"
          rm -f "$SYMLINK_PATH" 2>/dev/null || true
        fi
      fi
    fi

    # Archive agent directory for debugging (cleaned by clear-stale-locks.sh)
    ARCHIVE_DIR="${ACTIVE_DIR}/_archived"
    mkdir -p "$ARCHIVE_DIR" 2>/dev/null || true
    ARCHIVE_NAME="agent-$$-$(date +%Y%m%dT%H%M%S)"
    mv "$AGENT_HOME" "$ARCHIVE_DIR/$ARCHIVE_NAME" 2>/dev/null || rm -rf "$AGENT_HOME" 2>/dev/null || true
  fi

  # Clean up temp prompt files generated by socket-listener.mjs
  if [ -n "$PROMPT_FILE" ] && [[ "$PROMPT_FILE" == /tmp/${BOT_NAME}-prompt-* ]]; then
    rm -f "$PROMPT_FILE"
  fi
  # Clean up worktree if one was created
  if [ -n "$WORKTREE_DIR" ] && [ -d "$WORKTREE_DIR" ]; then
    cd "$PROJECT_CHECKOUT" 2>/dev/null || true
    git worktree remove "$WORKTREE_DIR" --force 2>/dev/null || true
  fi
}
